apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
spec:
  replicas: 3 #3 pods running
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two
        image: httpd:alpine
        ports:
        - containerPort: 80
        env:
          - name : APP_NAME
            value : "app2"
---
apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  selector:
    app: app-two
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
