apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: app-three
        image: containous/whoami
        ports:
        - containerPort: 80
        env:
          - name : APP_NAME
            value : "app3"
---
apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  selector:
    app: app-three
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
